### ISSUE TITLE
docker-compose.yml as argument

### ISSUE THREAD

**Issue by athoune** [factorysh/batch-scheduler#2]
Register a project, ie a folder with a docker-compose.yml file.

Some services can be a cronjob : it has two labels `prefix.cronjob.schedule` and `prefix.cronjob.command`

CPU / RAM use docker settings, MaxExectionTime is set with a label, `prefix.cronjob.max_execution_time`

`POST /api/schedule` with a JSON body, with a `compose` key.

**Comment by papey** [comment]
Now that we have a basic docker-compose support, it's time to add specific labels support.

**Comment by athoune** [comment]
See #8 and #9
